name: dickinson
favicon: null
layout_spectrum: 0.1932154295500368
typography_spectrum: 0.5796388296876103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7355570672079921
  lightness: 0.8654175428673625
  saturation: 0.978705495595932
  rhythmicContrast: 0.0031975561287254095
purpose: []
